{{- $secretName := printf "%s-admin" (include "clickhouse.fullname" .) -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
type: Opaque
data:
  admin: {{ if $existingSecret -}}
    {{ index $existingSecret.data "admin" }}
  {{- else -}}
    {{- default (randAlphaNum 16) .Values.adminPassword | b64enc | quote -}}
  {{- end }}
